export const blogs = [
    {
        slug: "amelia-wattenberger",
        title: "Amelia Wattenberger",
        author: "Amelia Wattenberger",
        url: "https://wattenberger.com",
        image: "https://wattenberger.com/favicon.svg",
        description:
            "\nA portfolio showcasing interactive data visualizations, design projects, and development work, with a focus on making complex data more accessible and engaging through innovative visual techniques.\n",
        startYear: "",
        postCount: "",
        tags: ["visualization", "design", "ai"],
    },
    {
        slug: "amos-wenger",
        title: "fasterthanli.me",
        author: "Amos Wenger",
        url: "https://fasterthanli.me",
        image: "",
        description:
            "\nAmos's blog offers in-depth tutorials and insights on Rust programming, focusing on helping developers understand and master the language through practical examples and detailed explanations.\n",
        startYear: "2024-05-28",
        postCount: "",
        tags: ["rust", "tutorials"],
    },
    {
        slug: "chris-ferdinandi",
        title: "Go Make Things",
        author: "Chris Ferdinandi",
        url: "https://gomakethings.com",
        image: "https://gomakethings.com/img/chris-ferdinandi-2.jpg",
        description:
            "\nChris Ferdinandi has advised and written code for organizations like NASA, Apple, Harvard Business School, Chobani, and Adidas. Chris Coyier, the founder of CodePen, has described his writing as “infinitely quote-worthy.”\n",
        startYear: "2011-01-19",
        postCount: "1000+",
        tags: ["javascript", "performance", "html"],
    },
    {
        slug: "dan-abramov",
        title: "overreacted",
        author: "Dan Abramov",
        url: "https://overreacted.io/",
        image: "https://github.com/gaearon.png",
        description:
            "\nA blog by Dan Abramov, co-author of Redux and Create React App, sharing deep insights and tutorials on JavaScript, React, and software development practices.\n",
        startYear: "",
        postCount: "",
        tags: ["react", "javascript", "frontend"],
    },
    {
        slug: "fredrik-soderstrom",
        title: "Writing JavaScript",
        author: "Fredrik Söderström",
        url: "https://writingjavascript.com",
        image: "https://writingjavascript.com/writing-javascript-og.webp?size=open-graph",
        description: "",
        startYear: "",
        postCount: "",
        tags: ["javascript"],
    },
    {
        slug: "josh-w-comeau",
        title: "Josh W Comeau",
        author: "Josh W Comeau",
        url: "https://www.joshwcomeau.com",
        image: "https://www.joshwcomeau.com/images/og-default.png",
        description:
            "\nFront-end web development tutorials and articles, focusing on React, CSS, JavaScript, and performance tips.\n",
        startYear: "",
        postCount: "",
        tags: ["frontend", "react", "css", "javascript"],
    },
    {
        slug: "matt-pockock",
        title: "Total Typescript",
        author: "Matt Pockock",
        url: "https://www.totaltypescript.com/articles",
        image: "https://www.totaltypescript.com/card@2x.png?date=12/15/23",
        description: "",
        startYear: "",
        postCount: "",
        tags: ["typescript", "javascript", "frontend"],
    },
    {
        slug: "max-stoiber",
        title: "Max Stoiber",
        author: "Max Stoiber",
        url: "https://mxstbr.com",
        image: "https://mxstbr.com/og",
        description:
            "\nA personal website that highlights the work and projects of Max Stoiber, focusing on technology, startups, web development, and contributions to the open-source community, especially in the React ecosystem.\n",
        startYear: "",
        postCount: "",
        tags: ["startups", "open-source", "react"],
    },
    {
        slug: "nicolas-hoizey",
        title: "Nicolas Hoizey",
        author: "Nicolas Hoizey",
        url: "https://nicolas-hoizey.com",
        image: "https://res.cloudinary.com/nho/image/upload/w_1200,h_630,c_fill,q_auto,f_auto/w_1100,c_fit,co_rgb:000000,g_south_west,x_50,y_380,l_text:Georgia_92:Articlesa/resources/opengraph-background",
        description: "",
        startYear: "",
        postCount: "",
        tags: ["design"],
    },
    {
        slug: "stefan-judis",
        title: "Stefan Judis",
        author: "Stefan Judis",
        url: "https://www.stefanjudis.com",
        image: "data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 100 100%22><text y=%22.9em%22 font-size=%2290%22>🧢</text></svg>",
        description:
            "\nA personal website featuring articles, tutorials, and resources on web development, with an emphasis on JavaScript, CSS, and modern frontend technologies.\n",
        startYear: "",
        postCount: "",
        tags: ["javascript", "css", "frontend"],
    },
    {
        slug: "troy-hunt",
        title: "Troy Hunt",
        author: "Troy Hunt",
        url: "https://www.troyhunt.com",
        image: "https://www.troyhunt.com/content/images/2017/01/1.jpg",
        description:
            "\nTroy Hunt's blog focuses on cybersecurity, data breaches, and privacy issues, offering expert analysis, advice, and insights into the latest security threats and best practices.\n",
        startYear: "",
        postCount: "",
        tags: ["cybersecurity", "hacking", "privacy"],
    },
    {
        slug: "werner-vogels",
        title: "All Things Distributed",
        author: "Werner Vogels",
        url: "https://www.allthingsdistributed.com/",
        image: "https://www.allthingsdistributed.com/images/wvlogo.jpg",
        description:
            "\nWerner Vogels, CTO of Amazon, discusses cloud computing, AWS innovations, and distributed systems, providing insights into scalable architecture and technology trends.\n",
        startYear: "2005-12-08",
        postCount: "400+",
        tags: ["cloud", "aws", "architecture"],
    },
];
