export const tags = {
    ai: "AI",
    architecture: "Architecture",
    aws: "AWS",
    cloud: "Cloud",
    css: "CSS",
    cybersecurity: "Cybersecurity",
    data: "Data",
    "data-breaches": "Data Breaches",
    design: "Design",
    "distributed-systems": "Distributed Systems",
    frontend: "Frontend",
    hacking: "Hacking",
    html: "HTML",
    javascript: "Javascript",
    "open-source": "Open Source",
    performance: "Performance",
    privacy: "Privacy",
    react: "React",
    rust: "Rust",
    security: "Security",
    startups: "Startups",
    technology: "Technology",
    tutorials: "Tutorials",
    typescript: "Typescript",
    visualization: "Visualization",
};
